### ISSUE TITLE
Espressif IDF Visual Studio Code crashes when loading the GUI Configuration Tool on Windows 10 - root cause and fix provided

### ISSUE THREAD

**Issue by dolhastelian** [espressif/ESP8266_RTOS_SDK#1057]
**Test Environment**
 - OS: Windows 10 Enterprise, Version 1909, OS build: 18363.1379
 - ESD IDF: release/v3.4-rc
 - target: esp8266
 - Espressif IDF Visual Studio Code extension version 1.0.0

**Note**: the issue appears only on Windows

**Steps to reproduce**
1. Create new project from examples (e.g hello_world)
2. Launch GUI Configuration Tool from VSCode taskbar

**The problem** 
- The GUI Configuration tool does not open

**Debug**
- ran separately from command line the idf confserver command to check where it hangs
- it seems that on Windows, the script has an issue to create temporary files in home directory
- the problem is in confserver.py file in the ESP IDF, it is not related to VS Code extension
output:
Traceback (most recent call last):
  File "D:/work/esp/sdk/ESP8266_RTOS_SDK/tools/kconfig_new/confserver.py", line 278, in <module>
    main()
  File "D:/work/esp/sdk/ESP8266_RTOS_SDK/tools/kconfig_new/confserver.py", line 65, in main
    run_server(args.kconfig, args.config)
  File "D:/work/esp/sdk/ESP8266_RTOS_SDK/tools/kconfig_new/confserver.py", line 76, in run_server
    deprecated_options.replace(sdkconfig_in=f_o.name, sdkconfig_out=sdkconfig)
  File "D:\work\esp\sdk\ESP8266_RTOS_SDK\tools\kconfig_new\confgen.py", line 102, in replace
    with open(sdkconfig_in, 'r') as f_in, open(sdkconfig_out, 'w') as f_out:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\AppData\\Local\\Temp\\**tmpv114t2jj**

the confserver.py script fails in function def run_server(kconfig, sdkconfig, default_version=MAX_PROTOCOL_VERSION):
when trying to create a temporary file

It seems that opening a file in Python and accessing it from multiple processes causes issues on Windows systems and the issue + potential fix is intensively discussed [https://stackoverflow.com/questions/15169101/how-to-create-a-temporary-file-that-can-be-read-by-a-subprocess/15235559#15235559](url).

**Solution**
- make sure the path to the temporary file is in a well known location / path (not one generated automatically) in home directory.
- please find the file with the fix attached to the issue
- [confserver.zip](https://github.com/espressif/ESP8266_RTOS_SDK/files/6027565/confserver.zip)
- code change summary 
![image](https://user-images.githubusercontent.com/3252394/108819406-294d3200-75fe-11eb-90bc-7b7d6225846b.png)

An alternative fix could be found, but this is simple and efficient

**Test**
With this change the GUI Configuration Tool starts successfully 

**Note**: fix not tested on Linux as well but no issue expected

**Comment by dolhastelian** [comment]
Hello Espressif,
is there any plan to fix this issue in the official release?
