### ISSUE TITLE
can't build docs (GIT8266O-826)

### ISSUE THREAD

**Issue by zoldseges** [espressif/ESP8266_RTOS_SDK#1249]
## Environment

- Development Kit:
- IDF version (``git rev-parse --short HEAD`` to get the commit id.):  89a3f254
- Development Env:      Make
- Operating System:     Ubuntu

## Problem Description

Can't build docs.

### Steps to repropduce

```sh
$ ESP8266_RTOS_SDK/docs/en: make html
```
## Debug Logs

```
Getting Doxyfile's INPUT
Generating 'api_name.inc' files with Doxygen directives
Traceback (most recent call last):
  File "/mnt/storage/tools/ESP8266_RTOS_SDK/docs/en/../gen-dxd.py", line 318, in <module>
    generate_api_inc_files()
  File "/mnt/storage/tools/ESP8266_RTOS_SDK/docs/en/../gen-dxd.py", line 276, in generate_api_inc_files
    rst_output = generate_directives(header_file_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/storage/tools/ESP8266_RTOS_SDK/docs/en/../gen-dxd.py", line 248, in generate_directives
    tree = ET.ElementTree(file=xml_file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 540, in __init__
    self.parse(file)
  File "/usr/lib/python3.11/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'xml/esp__wifi_8h.xml'

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/adam/.espressif/python_env/rtos3.4_py3.11_env/lib/python3.11/site-packages/sphinx/config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/storage/tools/ESP8266_RTOS_SDK/docs/en/conf.py", line 11, in <module>
    from conf_common import *
  File "/mnt/storage/tools/ESP8266_RTOS_SDK/docs/conf_common.py", line 59, in <module>
    call_with_python('../gen-dxd.py')
  File "/mnt/storage/tools/ESP8266_RTOS_SDK/docs/conf_common.py", line 47, in call_with_python
    raise RuntimeError('{} failed'.format(cmd))
RuntimeError: ../gen-dxd.py failed

make: *** [../docs_common.mk:68: html] Error 2
```

**Comment by wojtess** [comment]
same here, did you resolved it?

**Comment by zoldseges** [comment]
@wojtess no :(
